site_name: green-ee
# theme: psinder
markdown_extensions:
    - toc:
        permalink: True
nav:
    - Home: index.md
    - Power: responsibility.md
    - Why?: why.md
    - Whitepaper: ul.md
    - About: about.md